### PR TITLE
feat: added wrapper code for LEDGenerator and Agrawal Generator in generator.py

### PR DESCRIPTION
**Pull request by risheetperi**
Added classes in `capymoa/stream/generator.py` to initiate the respective classes which instantizes a MOA generator object. It has been done in a similar format as the 4 other generators in the code.

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @risheetperi , thanks for the PR. Let's wait for the automated tests to complete and then proceed to review the code

Cheers,
Heitor

**Comment by hmgomes** [comment]
Hi @risheetperi , there are still some errors with this PR, please see the output. It seems the error is related to the default parameters for AgrawalGenerator in the class documentation code example.

**Comment by risheetperi** [comment]
Hi, @hmgomes, Is it possible to run the checks on GitHub automatically when I push, or or will the checks only run if you or the supervisors run it?

**Comment by tachyonicClock** [comment]
@risheetperi I've approved you so it should run when you make changes.

**Comment by tachyonicClock** [comment]
@risheetperi If you install capymoa with dev dependencies `pip install -e '.[dev,doc]'` you can run the tests locally with `python -m invoke test`

**Comment by risheetperi** [comment]
Thanks, I will look into the error

**Comment by hmgomes** [comment]
Hi @risheetperi , please create another commit to remove the generated files from your commit (the outputs on the notebook directory), such as `notebooks/accuracy_HoeffdingAdaptiveTree_HoeffdingTree_AdaptiveRandomForestMB.pdf`

**Comment by risheetperi** [comment]
Hi @hmgomes, Should I remove all the files created today (except the .arff files) or only remove the pdfs?

**Comment by hmgomes** [comment]
Since the core modifications for this to work is on `src/capymoa/stream/generator.py` the other changes can be removed (including the additional files). It is very likely that you end up adding those output files unwillingly when adding the files to the commit.

**Comment by hmgomes** [comment]
It seems there are still 2 files to be removed: `notebooks/output.gif` and `notebooks/rootmeansquarederror_FIMTDD_kNNRegressor.pdf`

**Comment by risheetperi** [comment]
Hello @hmgomes , Can you please check the latest commit? Let me know if there are any more files I have to remove

**Comment by risheetperi** [comment]
Hello @hmgomes , Can you please check the latest commit? Let me know if there are any more files I have to remove. I just deleted the two files you asked me to.

It seems like the files are generated whenever I run the command `python -m invoke test`

**Pull request merged**
