### PR TITLE
feat: add ``restart_stream=False`` as an option in evaluators

### PR DESCRIPTION
**Pull request by tachyonicClock**

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @tachyonicClock  , this PR is adding some much needed code refactoring to the evaluation functions besides the param to avoid restarting the stream. We will need to coordinate with @YibinSun  because of https://github.com/adaptive-machine-learning/CapyMOA/pull/138

**Comment by tachyonicClock** [comment]
> Hi @tachyonicClock , this PR is adding some much needed code refactoring to the evaluation functions besides the param to avoid restarting the stream. We will need to coordinate with @YibinSun because of #138

I think we should merge #138 first and then I can rebase this.

**Comment by hmgomes** [comment]
Hi @tachyonicClock , should rebase or create a new PR altogether?

**Comment by tachyonicClock** [comment]
I'll take care of it tomorrow. I'll see how rebasing goes.

**Comment by tachyonicClock** [comment]
Might end up copy pasting 😁

**Review by hmgomes — APPROVED** [review]

**Pull request merged**
