### PR TITLE
feat: add wrapper for hyperplane (c and r) generators

### PR DESCRIPTION
**Pull request by YibinSun**
Add wrappers for HyperPlaneClassification and HyperPlandRegression generators

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @YibinSun thanks for pushing the generators. @nuwangunasekara can you take a look at it? I believe you were also using these generators or did I just share with you files generated with them? I can't remember at this point.

**Comment by nuwangunasekara** [comment]
@YibinSun and @hmgomes : PR looks okay to me.


Just checking whether we could use the ```build_cli_str_from_mapping_and_locals``` function as in ```_srp.py``` to process the options, which can be easy for some to understand.
We use sane defaults for init and process options when necessary. (**This may not apply to this case, just letting you know** )

**Comment by hmgomes** [comment]
> @YibinSun and @hmgomes : PR looks okay to me.
> 
> Just checking whether we could use the `build_cli_str_from_mapping_and_locals` function as in `_srp.py` to process the options, which can be easy for some to understand. We use sane defaults for init and process options when necessary. (**This may not apply to this case, just letting you know** )

Hi @YibinSun can you check if that is viable? Apparently, it should be possible. 
@nuwangunasekara I believe he was following SEA and RTG generators, both were created before `build_cli_str_from_mapping_and_locals` was available.

**Comment by YibinSun** [comment]
@hmgomes @nuwangunasekara Updated the wrapper. Please take a look.

**Comment by nuwangunasekara** [comment]
Sounds good 🙂
Thanks @YibinSun

**Comment by hmgomes** [comment]
thanks @YibinSun !

**Pull request merged**
