### PR TITLE
feat: add anomaly_threshold and size_limit parameters to HalfSpaceTree

### PR DESCRIPTION
**Pull request by justinuliu**
…es constructor

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @justinuliu , this change is more like a `fix` rather than `feat`

**Comment by hmgomes** [comment]
I have made some changes to the anomaly_detection tutorial, which caused a few conflicts with this one. Hopefully they can be easily resolved

**Comment by justinuliu** [comment]
> Hi @justinuliu , this change is more like a `fix` rather than `feat`

Sorry about that. Maybe I can re-submit a PR and resolve the conflict as well.

**Comment by hmgomes** [comment]
> > Hi @justinuliu , this change is more like a `fix` rather than `feat`
> 
> Sorry about that. Maybe I can re-submit a PR and resolve the conflict as well.

no worries, it will be fine :)

**Pull request merged**
