### PR TITLE
fix: stream restart

### PR DESCRIPTION
**Pull request by hmgomes**
Restart at the beginning of every evaluation function. 
Updated notebooks SSL_example and 06.

### CODE REVIEW

**Comment by hmgomes** [comment]
Hi @tachyonicClock , I've added you as reviewer since you are also familiar with the `*_ssl_evaluation` functions, even though this change goes beyond them. In summary, previously we used to restart the stream passed as a parameter only if there were no more instances to be processed. This was not ideal if someone was using a synthetic stream, there will always be new instances to be processed. It would become particularly confusing if we were using a stream with simulated drifts and multiple calls to `*_evaluation`. For example:

```
stream = DriftStream([...])
learner1 = ...
learner2 = ...
res1 = prequential_evaluation(stream, learner1, ...)
res2 = prequential_evaluation(stream, learner2, ...)
```
In this example, previously, the second call to `prequential_evaluation` would start off from where the first call stopped, which is not incorrect per se, but counterintuitive. Now, one thing that is a bit annoying is that I went to every high-level evaluation function and made this change.

**Comment by tachyonicClock** [comment]
This looks good. But it would be nice to have some tests that verify the behaviour.

**Comment by hmgomes** [comment]
Good point @tachyonicClock , going to add a test for the evaluation functions.

**Comment by hmgomes** [comment]
Added the tests for the evaluation functions. Also added tests for `test_then_train_ssl_evaluation` (renamed to `*_ssl_*` instead of `*_SSL_*` too) and `prequential_ssl_evaluation`, but the tests for these two could be improved.

**Comment by hmgomes** [comment]
#117 addresses the changes in this PR.

**Pull request closed without merging**
